/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlytvien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DIENMAYXANH
 */
public class frmGiaodienChinhTest extends javax.swing.JFrame {

    /**
     * Creates new form frmGiaodienchinh
     */
    public frmGiaodienChinhTest() {
        initComponents();
        clock();
        dt();
    }
    
    public void dt(){ //Hàm hiển thị ngày ra màn hình
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String dd = sdf.format(d);
        lbrD.setText(dd); //Đặt nội dung hiển thị cho dòng "Ngày"
    }
    
    private void clock(){ //Hàm hiển thị giờ ra màn hình
        new Thread(){
            public void run(){
                while (true){
                Calendar ca = new GregorianCalendar();
                int AM_PM = ca.get(Calendar.AM_PM);
                String day_night;
                if(AM_PM ==1){
                    day_night = "PM";
                }else{
                    day_night = "AM";
                }
                SimpleDateFormat sp = new SimpleDateFormat("HH:mm:ss");
                Date dat = ca.getTime();
                String time = sp.format(dat);
                lbrClock.setText(time + " " + day_night); //Đặt nội dung hiển thị cho dòng "Giờ"
            }    
            }      
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnGiaodienchinh = new com.k33ptoo.components.KGradientPanel();
        lbrClock = new javax.swing.JLabel();
        lbrD = new javax.swing.JLabel();
        btnThoatM = new com.k33ptoo.components.KButton();
        btnDangkyM = new com.k33ptoo.components.KButton();
        btnDangnhapM = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();
        pnGiaodiendangnhap = new com.k33ptoo.components.KGradientPanel();
        btnThoatDN = new com.k33ptoo.components.KButton();
        btnDangnhapDN = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBackDN = new javax.swing.JButton();
        cbType = new combobox.Combobox();
        chkShowDN = new javax.swing.JCheckBox();
        txtUsernameDN = new javax.swing.JTextField();
        txtPasswordDN = new javax.swing.JPasswordField();
        btnDangki = new javax.swing.JButton();
        pnGiaodiendangky = new com.k33ptoo.components.KGradientPanel();
        btnThoatDK = new com.k33ptoo.components.KButton();
        btnDangkyDK = new com.k33ptoo.components.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSDTDK = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtGmailDK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnBackDK = new javax.swing.JButton();
        chkShowDK = new javax.swing.JCheckBox();
        txtUsernameDK = new javax.swing.JTextField();
        txtPasswordDK = new javax.swing.JPasswordField();
        txtConfirmDK = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnGiaodienchinh.setBackground(new java.awt.Color(0, 153, 153));
        pnGiaodienchinh.setkBorderRadius(0);
        pnGiaodienchinh.setkEndColor(new java.awt.Color(0, 153, 153));
        pnGiaodienchinh.setkFillBackground(false);
        pnGiaodienchinh.setkStartColor(new java.awt.Color(0, 153, 153));

        lbrClock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbrClock.setForeground(new java.awt.Color(255, 255, 255));
        lbrClock.setText("Giờ");

        lbrD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbrD.setForeground(new java.awt.Color(255, 255, 255));
        lbrD.setText("Ngày");

        btnThoatM.setForeground(new java.awt.Color(0, 0, 0));
        btnThoatM.setText("Thoát");
        btnThoatM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoatM.setkAllowGradient(false);
        btnThoatM.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnThoatM.setkBorderRadius(20);
        btnThoatM.setkEndColor(new java.awt.Color(0, 0, 0));
        btnThoatM.setkForeGround(new java.awt.Color(0, 0, 0));
        btnThoatM.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnThoatM.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnThoatM.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnThoatM.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnThoatM.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnThoatM.setkStartColor(new java.awt.Color(0, 0, 0));
        btnThoatM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatMActionPerformed(evt);
            }
        });

        btnDangkyM.setForeground(new java.awt.Color(0, 0, 0));
        btnDangkyM.setText("Đăng ký");
        btnDangkyM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangkyM.setkAllowGradient(false);
        btnDangkyM.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangkyM.setkBorderRadius(20);
        btnDangkyM.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnDangkyM.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangkyM.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyMActionPerformed(evt);
            }
        });

        btnDangnhapM.setForeground(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setText("Đăng nhập");
        btnDangnhapM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangnhapM.setkAllowGradient(false);
        btnDangnhapM.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangnhapM.setkBorderRadius(20);
        btnDangnhapM.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnDangnhapM.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangnhapM.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapMActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("THƯ VIỆN ICTU");

        javax.swing.GroupLayout pnGiaodienchinhLayout = new javax.swing.GroupLayout(pnGiaodienchinh);
        pnGiaodienchinh.setLayout(pnGiaodienchinhLayout);
        pnGiaodienchinhLayout.setHorizontalGroup(
            pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaodienchinhLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodienchinhLayout.createSequentialGroup()
                        .addGroup(pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbrD)
                            .addComponent(lbrClock))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodienchinhLayout.createSequentialGroup()
                        .addGroup(pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnDangnhapM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDangkyM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThoatM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(63, 63, 63))))
        );
        pnGiaodienchinhLayout.setVerticalGroup(
            pnGiaodienchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodienchinhLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnDangnhapM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnDangkyM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnThoatM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(lbrClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbrD)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", pnGiaodienchinh);

        pnGiaodiendangnhap.setBackground(new java.awt.Color(0, 153, 153));
        pnGiaodiendangnhap.setkBorderRadius(0);
        pnGiaodiendangnhap.setkEndColor(new java.awt.Color(0, 153, 153));
        pnGiaodiendangnhap.setkFillBackground(false);
        pnGiaodiendangnhap.setkStartColor(new java.awt.Color(0, 153, 153));

        btnThoatDN.setForeground(new java.awt.Color(0, 0, 0));
        btnThoatDN.setText("Thoát");
        btnThoatDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoatDN.setkAllowGradient(false);
        btnThoatDN.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnThoatDN.setkBorderRadius(20);
        btnThoatDN.setkEndColor(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkForeGround(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnThoatDN.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnThoatDN.setkStartColor(new java.awt.Color(0, 0, 0));
        btnThoatDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatDNActionPerformed(evt);
            }
        });

        btnDangnhapDN.setForeground(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setText("Đăng nhập");
        btnDangnhapDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangnhapDN.setkAllowGradient(false);
        btnDangnhapDN.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangnhapDN.setkBorderRadius(20);
        btnDangnhapDN.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnDangnhapDN.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapDNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ĐĂNG NHẬP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bạn là?");

        btnBackDN.setBackground(new java.awt.Color(0, 0, 0));
        btnBackDN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBackDN.setForeground(new java.awt.Color(255, 255, 255));
        btnBackDN.setText("<");
        btnBackDN.setBorder(null);
        btnBackDN.setContentAreaFilled(false);
        btnBackDN.setDefaultCapable(false);
        btnBackDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDNActionPerformed(evt);
            }
        });

        cbType.setBackground(new java.awt.Color(0, 153, 153));
        cbType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        cbType.setForeground(new java.awt.Color(255, 255, 255));
        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Giảng viên", "Sinh viên" }));
        cbType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbType.setLabeText("");

        chkShowDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkShowDN.setForeground(new java.awt.Color(255, 255, 255));
        chkShowDN.setText("Show");
        chkShowDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowDNActionPerformed(evt);
            }
        });

        txtUsernameDN.setBackground(new java.awt.Color(0, 153, 153));
        txtUsernameDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsernameDN.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameDN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsernameDN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txtPasswordDN.setBackground(new java.awt.Color(0, 153, 153));
        txtPasswordDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordDN.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordDN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        btnDangki.setBackground(new java.awt.Color(242, 242, 242));
        btnDangki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangki.setForeground(new java.awt.Color(255, 255, 255));
        btnDangki.setText("Bạn chưa có tài khoản?");
        btnDangki.setBorder(null);
        btnDangki.setBorderPainted(false);
        btnDangki.setContentAreaFilled(false);
        btnDangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnGiaodiendangnhapLayout = new javax.swing.GroupLayout(pnGiaodiendangnhap);
        pnGiaodiendangnhap.setLayout(pnGiaodiendangnhapLayout);
        pnGiaodiendangnhapLayout.setHorizontalGroup(
            pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaodiendangnhapLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnGiaodiendangnhapLayout.createSequentialGroup()
                        .addComponent(btnBackDN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(83, 83, 83))
                    .addGroup(pnGiaodiendangnhapLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnGiaodiendangnhapLayout.createSequentialGroup()
                        .addGroup(pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnGiaodiendangnhapLayout.createSequentialGroup()
                                .addComponent(btnThoatDN, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(btnDangnhapDN, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(txtUsernameDN, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                .addComponent(txtPasswordDN))
                            .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkShowDN)
                            .addComponent(btnDangki))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnGiaodiendangnhapLayout.setVerticalGroup(
            pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodiendangnhapLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnBackDN))
                .addGap(50, 50, 50)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(chkShowDN)
                .addGap(27, 27, 27)
                .addGroup(pnGiaodiendangnhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoatDN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangnhapDN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnDangki)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", pnGiaodiendangnhap);

        pnGiaodiendangky.setBackground(new java.awt.Color(0, 153, 153));
        pnGiaodiendangky.setkBorderRadius(0);
        pnGiaodiendangky.setkEndColor(new java.awt.Color(0, 153, 153));
        pnGiaodiendangky.setkFillBackground(false);
        pnGiaodiendangky.setkStartColor(new java.awt.Color(0, 153, 153));

        btnThoatDK.setForeground(new java.awt.Color(0, 0, 0));
        btnThoatDK.setText("Thoát");
        btnThoatDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoatDK.setkAllowGradient(false);
        btnThoatDK.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnThoatDK.setkBorderRadius(20);
        btnThoatDK.setkEndColor(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkForeGround(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnThoatDK.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnThoatDK.setkStartColor(new java.awt.Color(0, 0, 0));
        btnThoatDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatDKActionPerformed(evt);
            }
        });

        btnDangkyDK.setForeground(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setText("Đăng ký");
        btnDangkyDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangkyDK.setkAllowGradient(false);
        btnDangkyDK.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangkyDK.setkBorderRadius(20);
        btnDangkyDK.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkHoverColor(new java.awt.Color(204, 204, 204));
        btnDangkyDK.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkHoverForeGround(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangkyDK.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyDKActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ĐĂNG KÝ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SDT:");

        txtSDTDK.setBackground(new java.awt.Color(0, 153, 153));
        txtSDTDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSDTDK.setForeground(new java.awt.Color(255, 255, 255));
        txtSDTDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gmail:");

        txtGmailDK.setBackground(new java.awt.Color(0, 153, 153));
        txtGmailDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGmailDK.setForeground(new java.awt.Color(255, 255, 255));
        txtGmailDK.setText("@gmail.com");
        txtGmailDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Confirm:");

        btnBackDK.setBackground(new java.awt.Color(0, 0, 0));
        btnBackDK.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBackDK.setForeground(new java.awt.Color(255, 255, 255));
        btnBackDK.setText("<");
        btnBackDK.setBorder(null);
        btnBackDK.setContentAreaFilled(false);
        btnBackDK.setDefaultCapable(false);
        btnBackDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDKActionPerformed(evt);
            }
        });

        chkShowDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkShowDK.setForeground(new java.awt.Color(255, 255, 255));
        chkShowDK.setText("Show");
        chkShowDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowDKActionPerformed(evt);
            }
        });

        txtUsernameDK.setBackground(new java.awt.Color(0, 153, 153));
        txtUsernameDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsernameDK.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtPasswordDK.setBackground(new java.awt.Color(0, 153, 153));
        txtPasswordDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordDK.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        txtConfirmDK.setBackground(new java.awt.Color(0, 153, 153));
        txtConfirmDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmDK.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnGiaodiendangkyLayout = new javax.swing.GroupLayout(pnGiaodiendangky);
        pnGiaodiendangky.setLayout(pnGiaodiendangkyLayout);
        pnGiaodiendangkyLayout.setHorizontalGroup(
            pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiaodiendangkyLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnGiaodiendangkyLayout.createSequentialGroup()
                        .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSDTDK, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGmailDK, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnGiaodiendangkyLayout.createSequentialGroup()
                                    .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnGiaodiendangkyLayout.createSequentialGroup()
                                            .addComponent(btnBackDK)
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(67, 67, 67)))
                            .addComponent(jLabel11))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(pnGiaodiendangkyLayout.createSequentialGroup()
                        .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnGiaodiendangkyLayout.createSequentialGroup()
                                    .addComponent(btnThoatDK, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(72, 72, 72)
                                    .addComponent(btnDangkyDK, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addComponent(jLabel8))
                            .addComponent(chkShowDK, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUsernameDK)
                            .addComponent(txtPasswordDK)
                            .addComponent(txtConfirmDK))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnGiaodiendangkyLayout.setVerticalGroup(
            pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiaodiendangkyLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btnBackDK))
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGmailDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDTDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(chkShowDK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnGiaodiendangkyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoatDK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangkyDK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", pnGiaodiendangky);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -30, 340, 615));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangnhapMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapMActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);//Khi nhấn vào nút "Đăng nhập" thì sẽ chuyển sang giao diện tương ứng
    }//GEN-LAST:event_btnDangnhapMActionPerformed

    private void btnDangkyMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyMActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);//Khi nhấn vào nút "Đăng ký" thì sẽ chuyển sang giao diện tương ứng
    }//GEN-LAST:event_btnDangkyMActionPerformed

    private void btnThoatMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatMActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thoát");
        if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn thoát không?","Thoát",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatMActionPerformed

    private void btnBackDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDNActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        txtUsernameDN.setText("");//Set lại giá trị cho dòng "Username" là rỗng
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnBackDNActionPerformed

    private void chkShowDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowDNActionPerformed
        // TODO add your handling code here:
        if (chkShowDN.isSelected()){
            txtPasswordDN.setEchoChar((char)0);
            
        }else{
            txtPasswordDN.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowDNActionPerformed

    private void btnThoatDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatDNActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thoát");
        if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn thoát không?","Thoát",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatDNActionPerformed

    private void btnDangnhapDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapDNActionPerformed
        // TODO add your handling code here:
        String username = txtUsernameDN.getText();
        String password = txtPasswordDN.getText();
        String type = cbType.getSelectedItem().toString();
        String sqlquery = "SELECT * FROM Taikhoan WHERE UserName=? AND uPassWord=? AND uType=?";
        try { //3 dòng đầu là câu lệnh để kết nối với SQL
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        PreparedStatement ps = con.prepareCall(sqlquery); //Thực thi câu truy vấn trong SQL
        ps.setString(1, username);
        ps.setString(2, password);
        ps.setString(3,type);
        ResultSet rs = ps.executeQuery(); //Lấy dữ liệu từ SQL bằng con trỏ
        if(txtUsernameDN.getText().equals("")){ //So sánh dòng Username với giá trị "rỗng"
            JOptionPane.showMessageDialog(this, "Bạn chưa điền Username");
            return;
        }else{
            if(txtPasswordDN.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn chưa điền Password");
                return;
        }else{
        if(rs.next()){ //So sánh dữ liệu lấy ra từ SQL với dữ liệu người dùng nhập vào
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            if(cbType.getSelectedIndex()==0){ //Nếu tư cách người dùng trùng với dòng "uType" trong bảng thì chuyển qua giao diện tương ứng
                frmGiaodienAdmin fr = new frmGiaodienAdmin();
                fr.setVisible(true);
                this.setVisible(false);
            }else{
                frmGiaodienUser fr = new frmGiaodienUser();
                fr.setVisible(true);
                this.setVisible(false);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Sai Username hoặc Password");
            return;
        }     
        }}}catch (Exception e) {
            
        }
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnDangnhapDNActionPerformed

    private void btnDangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkiActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnDangkiActionPerformed

    private void btnBackDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDKActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        txtSDTDK.setText("");
        txtUsernameDK.setText("");
        txtPasswordDK.setText("");
        txtConfirmDK.setText("");
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnBackDKActionPerformed

    private void chkShowDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowDKActionPerformed
        // TODO add your handling code here:
        if (chkShowDK.isSelected()){
            txtPasswordDK.setEchoChar((char)0);
            txtConfirmDK.setEchoChar((char)0);

        }else{
            txtPasswordDK.setEchoChar('*');
            txtConfirmDK.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowDKActionPerformed

    private void btnThoatDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatDKActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thoát");
        if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn thoát không?","Thoát",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatDKActionPerformed

    private void btnDangkyDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyDKActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        String sql = "insert into Taikhoan values (?,?,?,?,?,'Sinh viên')";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, txtGmailDK.getText());
        ps.setString(2, txtSDTDK.getText());
        ps.setString(3, txtUsernameDK.getText());
        ps.setString(4, txtPasswordDK.getText());
        ps.setString(5, txtConfirmDK.getText());

            int n = ps.executeUpdate();//update du lieu len SQL
            if(txtGmailDK.getText().equals("")|txtSDTDK.getText().equals("")|txtUsernameDK.getText().equals("")|txtPasswordDK.getText().equals("")|txtConfirmDK.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Không được để trống thông tin");
                return;
            }else{JFrame frame = new JFrame("Đăng ký");//Tạo tiêu đề cho thông báo
                if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn đăng ký không?","Đăng ký",
                    JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
            JOptionPane.showMessageDialog(this, "Đăng ký thành công");
        }
        } catch (Exception e) {
        }
        
        jTabbedPane1.setSelectedIndex(1);
        txtSDTDK.setText("");
        txtUsernameDK.setText("");
        txtPasswordDK.setText("");
        txtConfirmDK.setText("");
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnDangkyDKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGiaodienChinhTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGiaodienChinhTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGiaodienChinhTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGiaodienChinhTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGiaodienChinhTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackDK;
    private javax.swing.JButton btnBackDN;
    private javax.swing.JButton btnDangki;
    private com.k33ptoo.components.KButton btnDangkyDK;
    private com.k33ptoo.components.KButton btnDangkyM;
    private com.k33ptoo.components.KButton btnDangnhapDN;
    private com.k33ptoo.components.KButton btnDangnhapM;
    private com.k33ptoo.components.KButton btnThoatDK;
    private com.k33ptoo.components.KButton btnThoatDN;
    private com.k33ptoo.components.KButton btnThoatM;
    private combobox.Combobox cbType;
    private javax.swing.JCheckBox chkShowDK;
    private javax.swing.JCheckBox chkShowDN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbrClock;
    private javax.swing.JLabel lbrD;
    private com.k33ptoo.components.KGradientPanel pnGiaodienchinh;
    private com.k33ptoo.components.KGradientPanel pnGiaodiendangky;
    private com.k33ptoo.components.KGradientPanel pnGiaodiendangnhap;
    private javax.swing.JPasswordField txtConfirmDK;
    private javax.swing.JTextField txtGmailDK;
    private javax.swing.JPasswordField txtPasswordDK;
    private javax.swing.JPasswordField txtPasswordDN;
    private javax.swing.JTextField txtSDTDK;
    private javax.swing.JTextField txtUsernameDK;
    private javax.swing.JTextField txtUsernameDN;
    // End of variables declaration//GEN-END:variables
}
