/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.qlytvien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DIENMAYXANH
 */
public class frmThongtinUser extends javax.swing.JFrame {

    /**
     * Creates new form frmThongtinUser
     */
    public frmThongtinUser() {
        initComponents();
        show_Ndung();
    }
    public ArrayList<Ndung> ndList(){
        ArrayList<Ndung> ndList = new ArrayList<>();
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        String query1 = "SELECT * FROM TTBD";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query1);
        Ndung ndung;
        while(rs.next()){
            ndung = new Ndung(rs.getInt("STT"), rs.getString("MaBD"), rs.getString("MaSV"), rs.getString("Lop"), rs.getString("Khoa"), rs.getString("Hoten"), rs.getString("Gioitinh"), rs.getString("Ngaysinh"), rs.getString("SDT"), rs.getString("Gmail"), rs.getInt("Vipham"));
            ndList.add(ndung);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        return ndList;
        }
        public void show_Ndung(){
            ArrayList<Ndung> list = ndList();
            DefaultTableModel model = (DefaultTableModel) tblNdung.getModel();
            Object[] row = new Object[11];
            for (int i = 0; i < list.size(); i++) {
                row[0] = list.get(i).getSTT();
                row[1] = list.get(i).getMaBD();
                row[2] = list.get(i).getMaSV();
                row[3] = list.get(i).getLop();
                row[4] = list.get(i).getKhoa();
                row[5] = list.get(i).getHoten();
                row[6] = list.get(i).getGioitinh();
                row[7] = list.get(i).getNgaysinh();
                row[8] = list.get(i).getSDT();
                row[9] = list.get(i).getGmail();
                row[10] = list.get(i).getVipham();
                model.addRow(row);
            }
        }
        
        public void search(String str){
        DefaultTableModel model = (DefaultTableModel) tblNdung.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblNdung.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNdung = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaBd = new javax.swing.JTextField();
        txtMaSv = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbKhoa = new javax.swing.JComboBox<>();
        txtGmail = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        chbNam = new javax.swing.JCheckBox();
        chbNu = new javax.swing.JCheckBox();
        cDate = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtS = new javax.swing.JTextField();

        jTextField5.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNdung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã BĐ", "Mã SV", "Lớp", "Khoa", "Họ tên", "Giới tính", "Ngày sinh", "SDT", "Email", "Vi phạm"
            }
        ));
        tblNdung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNdungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNdung);
        if (tblNdung.getColumnModel().getColumnCount() > 0) {
            tblNdung.getColumnModel().getColumn(0).setMinWidth(40);
            tblNdung.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblNdung.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ THÔNG TIN BẠN ĐỌC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã bạn đọc:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã sinh viên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Lớp:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày sinh:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("SĐT:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Email:");

        txtMaBd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMaSv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtHoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Khoa:");

        cbKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ thông tin", "Công nghệ điện tử và truyền thông", "Công nghệ tự động hóa", "Hệ thống thông tin kinh tế", "Khoa học cơ bản", "Truyền thông đa phương tiện" }));

        txtGmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Reset");

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Giới tính:");

        buttonGroup1.add(chbNam);
        chbNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbNam.setText("Nam");

        buttonGroup1.add(chbNu);
        chbNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chbNu.setText("Nữ");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Search:");

        txtS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaSv)
                    .addComponent(txtLop)
                    .addComponent(cbKhoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaBd)
                    .addComponent(txtGmail))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbNam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(chbNu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSDT)
                    .addComponent(txtHoten)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35)
                        .addComponent(txtS))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThem)
                            .addComponent(btnReset))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(425, 425, 425))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtHoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbNam)
                            .addComponent(chbNu)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReset)
                            .addComponent(btnBack)
                            .addComponent(btnThoat)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        String query = "insert into TTBD(MaBD, MaSV, Lop, Khoa, Hoten, Gioitinh, Ngaysinh, SDT, Gmail, Vipham) values (?,?,?,?,?,?,?,?,?,'0')";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, txtMaBd.getText());
        ps.setString(2, txtMaSv.getText());
        ps.setString(3, txtLop.getText());
        String Khoa;
        Khoa = cbKhoa.getSelectedItem().toString();
        ps.setString(4, Khoa);
        ps.setString(5, txtHoten.getText());
        String Gioitinh = "";
        if(chbNam.isSelected()){
            Gioitinh += chbNam.getText()+"";
        }else{
            Gioitinh += chbNu.getText()+"";
        }
        ps.setString(6, Gioitinh);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(cDate.getDate());
        ps.setString(7, date);
        ps.setString(8, txtSDT.getText());
        ps.setString(9, txtGmail.getText());
        ps.executeUpdate(); //Update dữ liệu lên SQL
        //3 dòng sau để sau khi thêm xong thì bảng cũng sẽ tự cập nhật lại mà kh cần chạy lại phần mềm
        DefaultTableModel model = (DefaultTableModel) tblNdung.getModel();
        model.setRowCount(0); //setRowCount(0): trả về tất cả các hàng thỏa mãn điều kiện
        show_Ndung();
        JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblNdungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNdungMouseClicked
        // TODO add your handling code here:
        //Click để hiển thị từng dòng dữ liệu đã nhâp vào
        int i = tblNdung.getSelectedRow();
        TableModel model = tblNdung.getModel();
        txtMaBd.setText(model.getValueAt(i, 1).toString());
        txtMaSv.setText(model.getValueAt(i, 2).toString());
        txtLop.setText(model.getValueAt(i, 3).toString());
        String Khoa = model.getValueAt(i, 4).toString();
            switch(Khoa){
                case"Công nghệ thông tin":
                    cbKhoa.setSelectedIndex(0);
                    break;
                case"Công nghệ điện tử và truyền thông":
                    cbKhoa.setSelectedIndex(1);
                    break;
                case"Công nghệ tự động hóa":
                    cbKhoa.setSelectedIndex(2);
                    break;
                case"Hệ thống thông tin kinh tế":
                    cbKhoa.setSelectedIndex(3);
                    break;
                case"Khoa học cơ bản":
                    cbKhoa.setSelectedIndex(4);
                    break;
                case"Truyền thông đa phương tiện":
                    cbKhoa.setSelectedIndex(5);
                    break;
            }
        txtHoten.setText(model.getValueAt(i, 5).toString());
        String Gioitinh = model.getValueAt(i, 6).toString();
        if(Gioitinh.equals("Nam")){
            chbNam.setSelected(true);
        }else{
            chbNu.setSelected(true);
        }
        try {
            int srow = tblNdung.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(srow, 7));
            cDate.setDate(date);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        txtSDT.setText(model.getValueAt(i, 8).toString());
        txtGmail.setText(model.getValueAt(i, 9).toString());
        
    }//GEN-LAST:event_tblNdungMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int xn = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa dữ liệu không?", "Xoá", JOptionPane.YES_NO_OPTION);
        if(xn==0){
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        int row = tblNdung.getSelectedRow();
        String value = (tblNdung.getModel().getValueAt(row, 0).toString());
        String query = "DELETE FROM TTBD WHERE STT= "+value;
        PreparedStatement ps = con.prepareStatement(query);
        ps.executeUpdate();
        //3 dòng sau để sau khi xóa xong thì bảng cũng sẽ tự cập nhật lại mà kh cần chạy lại phần mềm
        DefaultTableModel model = (DefaultTableModel) tblNdung.getModel();
        model.setRowCount(0);
        show_Ndung();
        JOptionPane.showMessageDialog(this, "Xoá dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }}
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int xn = JOptionPane.showConfirmDialog(this,"Bạn có muốn sửa dữ liệu không?", "Sửa", JOptionPane.YES_NO_OPTION);
        if(xn==0){
        try {
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url = "jdbc:sqlserver://localhost\\HP:1433;databaseName=qlytvien;encrypt=true;trustServerCertificate=true;user=sa;password=572311";
        Connection con = DriverManager.getConnection(url);
        int row = tblNdung.getSelectedRow();
        String value = (tblNdung.getModel().getValueAt(row, 0).toString());
        String VP = (tblNdung.getModel().getValueAt(row, 10).toString());
        String query = "UPDATE TTBD SET MaBD=?, MaSV=?, Lop=?, Khoa=?, Hoten=?, Gioitinh=?, NgaySinh=?, SDT=?, Gmail=?, Vipham="+VP+" where STT="+value ;
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, txtMaBd.getText());
        ps.setString(2, txtMaSv.getText());
        ps.setString(3, txtLop.getText());
        String Khoa;
        Khoa = cbKhoa.getSelectedItem().toString();
        ps.setString(4, Khoa);
        ps.setString(5, txtHoten.getText());
        String Gioitinh = "";
        if(chbNam.isSelected()){
            Gioitinh += chbNam.getText()+"";
        }else{
            Gioitinh += chbNu.getText()+"";
        }
        ps.setString(6, Gioitinh);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date = df.format(cDate.getDate());
        ps.setString(7, date);
        ps.setString(8, txtSDT.getText());
        ps.setString(9, txtGmail.getText());
        ps.executeUpdate();
        DefaultTableModel model = (DefaultTableModel) tblNdung.getModel();//Lệnh để sau khi update data lên thì hiển thị luôn trên table
        model.setRowCount(0);//Lệnh để sau khi update data lên thì hiển thị luôn trên table
        show_Ndung();//Lệnh để sau khi update data lên thì hiển thị luôn trên table
        JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }}
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        frmGiaodienAdmin fr = new frmGiaodienAdmin();
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thoát");
        if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn thoát không?","Thoát",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void txtSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKeyReleased
        // TODO add your handling code here:
        String searchString = txtS.getText();
        search(searchString);
    }//GEN-LAST:event_txtSKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongtinUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongtinUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongtinUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongtinUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongtinUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser cDate;
    private javax.swing.JComboBox<String> cbKhoa;
    private javax.swing.JCheckBox chbNam;
    private javax.swing.JCheckBox chbNu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblNdung;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaBd;
    private javax.swing.JTextField txtMaSv;
    private javax.swing.JTextField txtS;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
