/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PM_QlyThuVien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DIENMAYXANH
 */
public class frm1_Giaodienchinh extends javax.swing.JFrame {

    /**
     * 
     */
    public frm1_Giaodienchinh() {
        initComponents();
    }
    
    public KetNoi kn = new KetNoi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JTabbedPane();
        Home_Page = new javax.swing.JPanel();
        panelRound3 = new PM_QlyThuVien.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        btnDangnhapHP = new com.k33ptoo.components.KButton();
        btnDangkyHP = new com.k33ptoo.components.KButton();
        btnThoatHP = new com.k33ptoo.components.KButton();
        Background2 = new javax.swing.JLabel();
        Dang_Nhap = new javax.swing.JPanel();
        panelRound1 = new PM_QlyThuVien.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnBackDN = new com.k33ptoo.components.KButton();
        btnDangnhap = new com.k33ptoo.components.KButton();
        jButton1 = new javax.swing.JButton();
        chkShowDN = new checkbox.JCheckBoxCustom();
        cbType = new combobox.Combobox_1();
        txtUsernameDN = new PM_QlyThuVien.TextField_1();
        txtPasswordDN = new PM_QlyThuVien.PasswordField();
        Background = new javax.swing.JLabel();
        Dang_Ky = new javax.swing.JPanel();
        panelRound2 = new PM_QlyThuVien.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        btnBackDK = new com.k33ptoo.components.KButton();
        btnDangky = new com.k33ptoo.components.KButton();
        chkShowDK = new checkbox.JCheckBoxCustom();
        txtGmailDK = new PM_QlyThuVien.TextField_1();
        txtSDTDK = new PM_QlyThuVien.TextField_1();
        txtUsernameDK = new PM_QlyThuVien.TextField_1();
        txtPasswordDK = new PM_QlyThuVien.PasswordField();
        txtConfirmDK = new PM_QlyThuVien.PasswordField();
        Background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_Page.setBackground(new java.awt.Color(255, 255, 255));
        Home_Page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound3.setBackground(new java.awt.Color(40, 42, 58));
        panelRound3.setRoundBottomLeft(25);
        panelRound3.setRoundBottomRight(25);
        panelRound3.setRoundTopLeft(25);
        panelRound3.setRoundTopRight(25);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("THƯ VIỆN ICTU");

        btnDangnhapHP.setText("Đăng nhập");
        btnDangnhapHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangnhapHP.setkAllowGradient(false);
        btnDangnhapHP.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangnhapHP.setkBorderRadius(20);
        btnDangnhapHP.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapHP.setkFillButton(false);
        btnDangnhapHP.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnDangnhapHP.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhapHP.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangnhapHP.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapHP.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangnhapHP.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhapHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapHPActionPerformed(evt);
            }
        });

        btnDangkyHP.setText("Đăng ký");
        btnDangkyHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangkyHP.setkAllowGradient(false);
        btnDangkyHP.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangkyHP.setkBorderRadius(20);
        btnDangkyHP.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyHP.setkFillButton(false);
        btnDangkyHP.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnDangkyHP.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangkyHP.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangkyHP.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyHP.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangkyHP.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangkyHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyHPActionPerformed(evt);
            }
        });

        btnThoatHP.setText("Thoát");
        btnThoatHP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThoatHP.setkAllowGradient(false);
        btnThoatHP.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnThoatHP.setkBorderRadius(20);
        btnThoatHP.setkEndColor(new java.awt.Color(0, 0, 0));
        btnThoatHP.setkFillButton(false);
        btnThoatHP.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnThoatHP.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnThoatHP.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnThoatHP.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnThoatHP.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnThoatHP.setkStartColor(new java.awt.Color(0, 0, 0));
        btnThoatHP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatHPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThoatHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangkyHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(134, 134, 134))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                            .addComponent(btnDangnhapHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(109, 109, 109)))))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(112, 112, 112)
                .addComponent(btnDangnhapHP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnDangkyHP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnThoatHP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        Home_Page.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 410, 510));

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add_BG/books-5433432_1280.jpg"))); // NOI18N
        Home_Page.add(Background2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        Menu.addTab("tab3", Home_Page);

        Dang_Nhap.setBackground(new java.awt.Color(255, 255, 255));
        Dang_Nhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(40, 42, 58));
        panelRound1.setRoundBottomLeft(25);
        panelRound1.setRoundBottomRight(25);
        panelRound1.setRoundTopLeft(25);
        panelRound1.setRoundTopRight(25);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        btnBackDN.setText("Back");
        btnBackDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBackDN.setkAllowGradient(false);
        btnBackDN.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnBackDN.setkBorderRadius(20);
        btnBackDN.setkEndColor(new java.awt.Color(0, 0, 0));
        btnBackDN.setkFillButton(false);
        btnBackDN.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnBackDN.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnBackDN.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBackDN.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnBackDN.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnBackDN.setkStartColor(new java.awt.Color(0, 0, 0));
        btnBackDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDNActionPerformed(evt);
            }
        });

        btnDangnhap.setText("Đăng nhập");
        btnDangnhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangnhap.setkAllowGradient(false);
        btnDangnhap.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangnhap.setkBorderRadius(20);
        btnDangnhap.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhap.setkFillButton(false);
        btnDangnhap.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnDangnhap.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangnhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangnhap.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhap.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangnhap.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangnhapActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(40, 42, 58));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bạn chưa có tài khoản?");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkShowDN.setBackground(new java.awt.Color(40, 42, 58));
        chkShowDN.setForeground(new java.awt.Color(255, 255, 255));
        chkShowDN.setText("Show");
        chkShowDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkShowDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowDNActionPerformed(evt);
            }
        });

        cbType.setBackground(new java.awt.Color(40, 42, 58));
        cbType.setForeground(new java.awt.Color(255, 255, 255));
        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thủ thư", "Bạn đọc" }));
        cbType.setSelectedIndex(-1);
        cbType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbType.setLabeText("Bạn là?");
        cbType.setLineColor(new java.awt.Color(255, 255, 255));

        txtUsernameDN.setBackground(new java.awt.Color(40, 42, 58));
        txtUsernameDN.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsernameDN.setLabelText("Username");
        txtUsernameDN.setLineColor(new java.awt.Color(255, 255, 255));

        txtPasswordDN.setBackground(new java.awt.Color(40, 42, 58));
        txtPasswordDN.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordDN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordDN.setLabelText("Password");
        txtPasswordDN.setLineColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chkShowDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRound1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(btnBackDN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUsernameDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPasswordDN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkShowDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackDN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        Dang_Nhap.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 410, 510));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add_BG/books-5433432_1280.jpg"))); // NOI18N
        Dang_Nhap.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        Menu.addTab("tab1", Dang_Nhap);

        Dang_Ky.setBackground(new java.awt.Color(255, 255, 255));
        Dang_Ky.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(40, 42, 58));
        panelRound2.setRoundBottomLeft(25);
        panelRound2.setRoundBottomRight(25);
        panelRound2.setRoundTopLeft(25);
        panelRound2.setRoundTopRight(25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ĐĂNG KÝ");

        btnBackDK.setText("Back");
        btnBackDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBackDK.setkAllowGradient(false);
        btnBackDK.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnBackDK.setkBorderRadius(20);
        btnBackDK.setkEndColor(new java.awt.Color(0, 0, 0));
        btnBackDK.setkFillButton(false);
        btnBackDK.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnBackDK.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnBackDK.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBackDK.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnBackDK.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnBackDK.setkStartColor(new java.awt.Color(0, 0, 0));
        btnBackDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackDKActionPerformed(evt);
            }
        });

        btnDangky.setText("Đăng ký");
        btnDangky.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDangky.setkAllowGradient(false);
        btnDangky.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnDangky.setkBorderRadius(20);
        btnDangky.setkEndColor(new java.awt.Color(0, 0, 0));
        btnDangky.setkFillButton(false);
        btnDangky.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnDangky.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnDangky.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangky.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnDangky.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnDangky.setkStartColor(new java.awt.Color(0, 0, 0));
        btnDangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangkyActionPerformed(evt);
            }
        });

        chkShowDK.setBackground(new java.awt.Color(40, 42, 58));
        chkShowDK.setForeground(new java.awt.Color(255, 255, 255));
        chkShowDK.setText("Show");
        chkShowDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkShowDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowDKActionPerformed(evt);
            }
        });

        txtGmailDK.setBackground(new java.awt.Color(40, 42, 58));
        txtGmailDK.setForeground(new java.awt.Color(255, 255, 255));
        txtGmailDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGmailDK.setLabelText("Gmail");
        txtGmailDK.setLineColor(new java.awt.Color(255, 255, 255));

        txtSDTDK.setBackground(new java.awt.Color(40, 42, 58));
        txtSDTDK.setForeground(new java.awt.Color(255, 255, 255));
        txtSDTDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSDTDK.setLabelText("Số điện thoại");
        txtSDTDK.setLineColor(new java.awt.Color(255, 255, 255));

        txtUsernameDK.setBackground(new java.awt.Color(40, 42, 58));
        txtUsernameDK.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsernameDK.setLabelText("Username");
        txtUsernameDK.setLineColor(new java.awt.Color(255, 255, 255));

        txtPasswordDK.setBackground(new java.awt.Color(40, 42, 58));
        txtPasswordDK.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPasswordDK.setLabelText("Password");
        txtPasswordDK.setLineColor(new java.awt.Color(255, 255, 255));

        txtConfirmDK.setBackground(new java.awt.Color(40, 42, 58));
        txtConfirmDK.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmDK.setLabelText("Confirm");
        txtConfirmDK.setLineColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(btnBackDK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkShowDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGmailDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSDTDK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsernameDK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPasswordDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConfirmDK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(91, 91, 91))))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(txtGmailDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSDTDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsernameDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkShowDK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackDK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangky, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        Dang_Ky.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 410, 510));

        Background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add_BG/books-5433432_1280.jpg"))); // NOI18N
        Dang_Ky.add(Background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 630));

        Menu.addTab("tab2", Dang_Ky);

        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1120, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangnhapHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapHPActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(1);
    }//GEN-LAST:event_btnDangnhapHPActionPerformed

    private void btnDangkyHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyHPActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(2);
    }//GEN-LAST:event_btnDangkyHPActionPerformed

    private void btnThoatHPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatHPActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Thoát");
        if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn thoát không?","Thoát",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatHPActionPerformed

    private void btnBackDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDNActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(0);
        cbType.setSelectedIndex(0);
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnBackDNActionPerformed

    private void btnBackDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackDKActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(1);
        txtSDTDK.setText("");
        txtUsernameDK.setText("");
        txtPasswordDK.setText("");
        txtConfirmDK.setText("");
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
        cbType.setSelectedIndex(0);
    }//GEN-LAST:event_btnBackDKActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Menu.setSelectedIndex(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangnhapActionPerformed
        // TODO add your handling code here:
        String username = txtUsernameDN.getText();
        String password = txtPasswordDN.getText();
        String type = cbType.getSelectedItem().toString();
        try {
        Connection con = kn.getConnection();
        String sqlquery = "SELECT * FROM Taikhoan WHERE UserName=? AND uPassWord=? AND uType=?";
        PreparedStatement ps = con.prepareCall(sqlquery); //Thực thi câu truy vấn trong SQL
        ps.setString(1, username);
        ps.setString(2, password);
        ps.setString(3,type);
        ResultSet rs = ps.executeQuery(); //Lấy dữ liệu từ SQL bằng con trỏ
        if(txtUsernameDN.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bạn chưa điền Username");
            return;
        }else{
            if(txtPasswordDN.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn chưa điền Password");
                return;
        }else{
        if(rs.next()){ //So sánh dữ liệu lấy ra từ SQL với dữ liệu người dùng nhập vào
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
            if(cbType.getSelectedIndex()==0){ //Nếu tư cách người dùng trùng với dòng "uType" trong bảng SQL thì chuyển qua giao diện tương ứng
                frm2_Thuthu fr = new frm2_Thuthu();
                fr.setVisible(true);
                this.setVisible(false);
            }else{
                frm3_Bandoc fr = new frm3_Bandoc();
                fr.setVisible(true);
                this.setVisible(false);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Sai Username hoặc Password");
            return;
        }     
        }}}catch (Exception e) {
            
        }
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnDangnhapActionPerformed

    private void btnDangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangkyActionPerformed
        // TODO add your handling code here:
        String P = txtPasswordDK.getText();
        String C = txtConfirmDK.getText();
        try {
        Connection con = kn.getConnection();
        String sql = "insert into Taikhoan values (?,?,?,?,?,?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, txtGmailDK.getText());
        ps.setString(2, txtSDTDK.getText());
        ps.setString(3, txtUsernameDK.getText());
        ps.setString(4, txtPasswordDK.getText());
        ps.setString(5, txtConfirmDK.getText());
        ps.setString(6,"Bạn đọc");
            if(txtGmailDK.getText().equals("")|txtSDTDK.getText().equals("")|txtUsernameDK.getText().equals("")|txtPasswordDK.getText().equals("")|txtConfirmDK.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Không được để trống thông tin");
                return;
            }
            if(!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z]+[.]{1}+[a-zA-Z]+$", txtGmailDK.getText()))){
                JOptionPane.showMessageDialog(this, "Email không đúng định dạng");
                return;
            }
            if(!(Pattern.matches("^0\\d{9}$", txtSDTDK.getText()))){
                JOptionPane.showMessageDialog(this, "SDT không đúng định dạng");
                return;
            }
            
            if(!C.equals(P)){
                JOptionPane.showMessageDialog(this, "Password không khớp!");
                return;
            }
            else{JFrame frame = new JFrame("Đăng ký");
                if(JOptionPane.showConfirmDialog(frame,"Bạn có muốn đăng ký không?","Đăng ký",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
                ps.executeUpdate();//update du lieu len SQL
        }else{
                    return;
                }
        }} catch (Exception e) {
        }
        
        Menu.setSelectedIndex(1);
        txtGmailDK.setText("");
        txtSDTDK.setText("");
        txtUsernameDK.setText("");
        txtPasswordDK.setText("");
        txtConfirmDK.setText("");
        txtUsernameDN.setText("");
        txtPasswordDN.setText("");
    }//GEN-LAST:event_btnDangkyActionPerformed

    private void chkShowDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowDKActionPerformed
        // TODO add your handling code here:
        if (chkShowDK.isSelected()){
            txtPasswordDK.setEchoChar((char)0);
            txtConfirmDK.setEchoChar((char)0);

        }else{
            txtPasswordDK.setEchoChar('*');
            txtConfirmDK.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowDKActionPerformed

    private void chkShowDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowDNActionPerformed
        // TODO add your handling code here:
        if (chkShowDN.isSelected()){
            txtPasswordDN.setEchoChar((char)0);
            
        }else{
            txtPasswordDN.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowDNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm1_Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm1_Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm1_Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm1_Giaodienchinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm1_Giaodienchinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background1;
    private javax.swing.JLabel Background2;
    private javax.swing.JPanel Dang_Ky;
    private javax.swing.JPanel Dang_Nhap;
    private javax.swing.JPanel Home_Page;
    private javax.swing.JTabbedPane Menu;
    private com.k33ptoo.components.KButton btnBackDK;
    private com.k33ptoo.components.KButton btnBackDN;
    private com.k33ptoo.components.KButton btnDangky;
    private com.k33ptoo.components.KButton btnDangkyHP;
    private com.k33ptoo.components.KButton btnDangnhap;
    private com.k33ptoo.components.KButton btnDangnhapHP;
    private com.k33ptoo.components.KButton btnThoatHP;
    private combobox.Combobox_1 cbType;
    private checkbox.JCheckBoxCustom chkShowDK;
    private checkbox.JCheckBoxCustom chkShowDN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private PM_QlyThuVien.PanelRound panelRound1;
    private PM_QlyThuVien.PanelRound panelRound2;
    private PM_QlyThuVien.PanelRound panelRound3;
    private PM_QlyThuVien.PasswordField txtConfirmDK;
    private PM_QlyThuVien.TextField_1 txtGmailDK;
    private PM_QlyThuVien.PasswordField txtPasswordDK;
    private PM_QlyThuVien.PasswordField txtPasswordDN;
    private PM_QlyThuVien.TextField_1 txtSDTDK;
    private PM_QlyThuVien.TextField_1 txtUsernameDK;
    private PM_QlyThuVien.TextField_1 txtUsernameDN;
    // End of variables declaration//GEN-END:variables
}
