/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PM_QlyThuVien;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DIENMAYXANH
 */
public class frm4_DoiMK extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public frm4_DoiMK() {
        initComponents();
    }
    
    public KetNoi kn = new KetNoi();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new PM_QlyThuVien.PanelRound();
        txtUs = new PM_QlyThuVien.TextField_1();
        txtPassC = new PM_QlyThuVien.PasswordField();
        txtPassM = new PM_QlyThuVien.PasswordField();
        txtConfirmM = new PM_QlyThuVien.PasswordField();
        chkShow = new checkbox.JCheckBoxCustom();
        btnReset = new com.k33ptoo.components.KButton();
        btnOK = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(36, 45, 54));

        txtUs.setBackground(new java.awt.Color(40, 42, 58));
        txtUs.setForeground(new java.awt.Color(255, 255, 255));
        txtUs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUs.setLabelText("Nhập username");
        txtUs.setLineColor(new java.awt.Color(255, 255, 255));

        txtPassC.setBackground(new java.awt.Color(40, 42, 58));
        txtPassC.setForeground(new java.awt.Color(255, 255, 255));
        txtPassC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassC.setLabelText("Nhập mật khẩu cũ");
        txtPassC.setLineColor(new java.awt.Color(255, 255, 255));

        txtPassM.setBackground(new java.awt.Color(40, 42, 58));
        txtPassM.setForeground(new java.awt.Color(255, 255, 255));
        txtPassM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPassM.setLabelText("Nhập mật khẩu mới");
        txtPassM.setLineColor(new java.awt.Color(255, 255, 255));

        txtConfirmM.setBackground(new java.awt.Color(40, 42, 58));
        txtConfirmM.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConfirmM.setLabelText("Xác nhận mật khẩu mới");
        txtConfirmM.setLineColor(new java.awt.Color(255, 255, 255));

        chkShow.setBackground(new java.awt.Color(40, 42, 58));
        chkShow.setForeground(new java.awt.Color(255, 255, 255));
        chkShow.setText("Show");
        chkShow.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setkAllowGradient(false);
        btnReset.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnReset.setkBorderRadius(20);
        btnReset.setkEndColor(new java.awt.Color(0, 0, 0));
        btnReset.setkFillButton(false);
        btnReset.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnReset.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnReset.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnReset.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnReset.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnReset.setkStartColor(new java.awt.Color(0, 0, 0));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOK.setkAllowGradient(false);
        btnOK.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        btnOK.setkBorderRadius(20);
        btnOK.setkEndColor(new java.awt.Color(0, 0, 0));
        btnOK.setkFillButton(false);
        btnOK.setkHoverColor(new java.awt.Color(30, 32, 44));
        btnOK.setkHoverEndColor(new java.awt.Color(0, 0, 0));
        btnOK.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnOK.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        btnOK.setkSelectedColor(new java.awt.Color(0, 0, 0));
        btnOK.setkStartColor(new java.awt.Color(0, 0, 0));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Đổi mật khẩu");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPassC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPassM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtConfirmM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chkShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(109, 109, 109))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfirmM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowActionPerformed
        // TODO add your handling code here:
        if (chkShow.isSelected()){
            txtPassC.setEchoChar((char)0);
            txtPassM.setEchoChar((char)0);
            txtConfirmM.setEchoChar((char)0);

        }else{
            txtPassC.setEchoChar('*');
            txtPassM.setEchoChar('*');
            txtConfirmM.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtUs.setText("");
        txtPassC.setText("");
        txtPassM.setText("");
        txtConfirmM.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        String username = txtUs.getText();
        String password = txtPassC.getText();
        String password1 = txtPassM.getText();
        String confirm = txtConfirmM.getText();
        String sqlquery = "SELECT * FROM Taikhoan WHERE UserName=? AND uPassWord=?";
        try {
            Connection con = kn.getConnection();
            PreparedStatement ps = con.prepareCall(sqlquery);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "Thông tin không khớp");
                return;
            }
            if(!password1.equals(confirm)){
                JOptionPane.showMessageDialog(this, "Pasword và Confirm không trùng nhau");
                return;
            }
            else{
                String query2 = "UPDATE Taikhoan SET uPassWord=?, Confirm=? WHERE UserName =?";
                PreparedStatement p1 = con.prepareStatement(query2);
                p1.setString(1, password1);
                p1.setString(2, confirm);
                p1.setString(3, username);
                p1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            }

        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm4_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm4_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm4_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm4_DoiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm4_DoiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnOK;
    private com.k33ptoo.components.KButton btnReset;
    private checkbox.JCheckBoxCustom chkShow;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private PM_QlyThuVien.PanelRound panelRound1;
    private PM_QlyThuVien.PasswordField txtConfirmM;
    private PM_QlyThuVien.PasswordField txtPassC;
    private PM_QlyThuVien.PasswordField txtPassM;
    private PM_QlyThuVien.TextField_1 txtUs;
    // End of variables declaration//GEN-END:variables
}
